package com.drclaude.ui

import androidx.compose.runtime.compositionLocalOf
import com.drclaude.data.Trend

enum class Lang(val code: String) { FR("FR"), ES("ES") }

fun langFromCode(code: String?): Lang = if (code == "es") Lang.ES else Lang.FR

/** All user-facing static strings, per language. Dynamic AI text + voice are
 *  localised server-side via the `lang` sent to the coach function. */
data class Strings(
    val sensor: String,
    val current: String,
    val updated: String,
    val waiting: String,
    val average: String,
    val target: String,
    val statHigh: String,
    val statLow: String,
    // Period label shown above the History/GÉNÉRAL stat boxes + TIR bar, so the window is never
    // ambiguous: "Dernières 24 h" (one day / Tout), "Sur les N derniers jours" (Tout, multi-day),
    // or "Le dd/MM" (a day chip selected). %d = day count, %s = formatted date.
    val periodLast24h: String,
    val periodOverDays: String,
    val periodOnDay: String,
    val periodFromTo: String,
    val deviation: String,
    val history: String,
    val talkToMom: String,
    val momTitle: String,
    val analyze: String,
    val listening: String,
    val statusHigh: String,
    val statusLow: String,
    val statusInRange: String,
    val loginSubtitle: String,
    val emailLabel: String,
    val passwordLabel: String,
    val connect: String,
    val howItWorks: String,
    val howItWorksBody: String,
    val trendFallingFast: String,
    val trendFalling: String,
    val trendStable: String,
    val trendRising: String,
    val trendRisingFast: String,
    val trendStuckHigh: String,
    val trendStuckLow: String,
    val tabGlucose: String,
    val tabMeals: String,
    val tabProfile: String,
    val profileTitle: String,
    val profileIntro: String,
    val fieldNickname: String,
    val fieldAge: String,
    val fieldWeight: String,
    val fieldDxYears: String,
    val fieldRapidName: String,
    val fieldRapidUnits: String,
    val fieldBasalName: String,
    val fieldBasalUnits: String,
    val fieldNotes: String,
    val saveProfile: String,
    /** Shown while the profile writes itself (there is no save button any more). */
    val autoSaving: String,
    val profileSaved: String,
    val ratiosEstimated: String,
    val ratiosDoctor: String,
    val foodTitle: String,
    val foodSoon: String,
    val foodDescHint: String,
    val foodCarbsHint: String,
    val foodQtyHint: String,
    val foodQtyTotal: String,
    val foodAdd: String,
    val foodVoiceHint: String,
    val foodEmpty: String,
    val foodPlanned: String,
    val foodEaten: String,
    val foodDelete: String,
    val foodDeleteConfirm: String,
    val foodScan: String,
    val foodScanning: String,
    val foodScanFail: String,
    val seeAllHistory: String,
    val filterAll: String,
    val historyScreenTitle: String,
    val generalTab: String,
    val pastAnalyses: String,
    val injections: String,
    val historyEmpty: String,
    val back: String,
    val alertLow: String,
    val alertHigh: String,
    val alertRapidRise: String,
    val alertRapidFall: String,
    val alertActLow: String,
    val alertActLowWait: String,
    val alertActHigh: String,
    val alertActFall: String,
    val alertActRise: String,
    val remindersLabel: String,
    val remindersSub: String,
    val alarmLabel: String,
    val alarmSub: String,
    // Notifications & alarms management page
    val notifCardTitle: String,
    val notifCardSub: String,
    val notifPageTitle: String,
    val notifModeTitle: String,
    val notifModeSound: String,
    val notifModeVibrate: String,
    val notifModeSilent: String,
    val notifVolumeLabel: String,
    val notifTestBtn: String,
    val notifQuietTitle: String,
    val notifQuietLabel: String,
    val notifQuietSub: String,
    val notifQuietFrom: String,
    val notifQuietTo: String,
    val notifTypesTitle: String,
    val notifHyperLabel: String,
    val notifHyperSub: String,
    val notifHypoLabel: String,
    val notifHypoSub: String,
    val notifHypoWarn: String,
    val notifHypoAlwaysLabel: String,
    val notifHypoAlwaysSub: String,
    val notifHypoVibrateActive: String,
    val notifHypoVibrateTitle: String,
    val notifHypoVibrateBody: String,
    val notifHypoVibrateConfirm: String,
    val notifFallLabel: String,
    val notifFallSub: String,
    val notifTelegramNote: String,
    val alertStop: String,
    val signalLost: String,
    val noSignal: String,
    val noSignalSub: String,
    val graphHidden: String,
    val noSignalShort: String,
    val accountsTitle: String,
    val accountsSub: String,
    val addAccount: String,
    val accountActive: String,
    val removeAccountConfirm: String,
    val yourProfiles: String,
    val addAccountTitle: String,
    val cancel: String,
    val consentTitle: String,
    val consentBody: String,
    val consentCheck: String,
    val consentAccept: String,
    val doseDisclaimer: String,
    val safetyTitle: String,
    val safetyBody: String,
    val safetyOk: String,
    val voiceLabel: String,
    val voiceSub: String,
    val statsPeriod: String,
    val online: String,
    val offline: String,
    val charging: String,
    val predictTitle: String,
    val predictHighSoon: String,
    val predictWatchFall: String,
    val predictWatchRise: String,
    val mealNudgeText: String,
    val mealNudgeLog: String,
    val byokTitle: String,
    val byokSub: String,
    val byokHint: String,
    val byokHelp: String,
    val byokSaved: String,
    val nativeVoiceLabel: String,
    val nativeVoiceSub: String,
    val autotuneTitle: String,
    val autotuneSub: String,
    val autotuneBtn: String,
    val autotuneApply: String,
    val donateTitle: String,
    val donateSub: String,
    val donateBtn: String,
    val hostedTitle: String,
    val hostedSub: String,
    val googleTitle: String,
    val googleSub: String,
    val googleBtn: String,
    val comingSoon: String,
    val healthTitle: String,
    val healthSub: String,
    val healthConnect: String,
    val healthInstall: String,
    val healthUnavailable: String,
    val healthHr: String,
    val healthSteps: String,
    val onDeviceData: String,
    // Insulin page
    val tabInsulin: String,
    val insulinTitle: String,
    val insulinIntro: String,
    val insulinUnitsHint: String,
    val insulinNameHint: String,
    val insulinActive: String,
    val insulinActiveExplain: String,
    val insulinEmpty: String,
    val insulinLogged: String,
    val saveFailed: String,
    // Global "a service fell" banner (any backend call failing — DB/history/stats/AI/credits)
    val serviceDownReach: String,
    val serviceDownCredits: String,
    val serviceDownRate: String,
    val serviceDownAuth: String,
    val serviceDownAi: String,
    // Sugar-vs-insulin tug-of-war (Insulin → Réglages tab)
    val tugTitle: String,
    val tugSugarWins: String,
    val tugInsulinWins: String,
    val tugTie: String,
    val tugNeutral: String,
    val tugDisclaimer: String,
    val tugActionSugar: String,
    val tugActionInsulin: String,
    val tugActionTie: String,
    val insulinRecent: String,
    // Backdating a forgotten meal/dose (the "Quand ?" picker)
    val whenLabel: String,
    val whenNow: String,
    val whenTitle: String,
    val whenToday: String,
    val whenYesterday: String,
    val editTitle: String,
    val editSave: String,
    val profTabProfile: String,
    val profTabNotifs: String,
    val profTabSettings: String,
    val deleteEntry: String,
    // Insulin settings (plain-language ratios) + suggestion, shown on the Insulin page
    val insulinSettingsTitle: String,
    val insulinSettingsCarb: String,
    val insulinSettingsCorr: String,
    val insulinSettingsTarget: String,
    val insulinSettingsNone: String,
    // AI gating
    val aiNeedsKey: String,
    val aiError: String,
    // Health Connect on/off + manage
    val healthUseLabel: String,
    val healthUseSub: String,
    val healthManage: String,
    // Clear local data
    val clearDataTitle: String,
    val clearDataSub: String,
    val clearDataBtn: String,
    val clearDataDone: String,
    // Doctor ratios (editable)
    val fieldCarbRatio: String,
    val fieldCorrection: String,
    val fieldTarget: String,
    val ratiosOptional: String,
    // Scan from gallery + replay voice
    val scanGallery: String,
    val replayVoice: String,
    val stopVoice: String,
    // Insulin ratio visual (2 cards) + applied confirmation, and Health Connect manual route
    val ratioVisualTitle: String,
    val ratioVisualUnit: String,
    val ratioVisualCubes: String,
    val ratioVisualGrams: String,
    val ratioApplied: String,
    val healthOpenApp: String,
    val ratioCurrentVsProposed: String,
    // Add-via-dialog flow + Insulin tabs + compact Food action labels
    val foodAddTitle: String,
    val insulinAddTitle: String,
    val insulinTabDoses: String,
    val insulinTabSettings: String,
    val foodScanShort: String,
    val foodGalleryShort: String,
    val insulinRapidTag: String,
    val insulinSlowTag: String,
) {
    fun trend(t: Trend): String = when (t) {
        Trend.FALLING_FAST -> trendFallingFast
        Trend.FALLING -> trendFalling
        Trend.RISING -> trendRising
        Trend.RISING_FAST -> trendRisingFast
        Trend.STABLE -> trendStable
        Trend.UNKNOWN -> "" // no arrow data → no word (was wrongly showing "Stable")
    }
}

val StringsFr = Strings(
    sensor = "Capteur FreeStyle",
    current = "ACTUEL",
    updated = "MAJ",
    waiting = "En attente de mesures…",
    average = "MOYENNE",
    target = "CIBLE",
    statHigh = "% HAUT",
    statLow = "% BAS",
    periodLast24h = "DERNIÈRES 24 H",
    periodOverDays = "%d DERNIERS JOURS",
    periodOnDay = "LE %s",
    periodFromTo = "DU %1\$s AU %2\$s",
    deviation = "ÉCART",
    history = "HISTORIQUE",
    talkToMom = "PARLER",
    momTitle = "DOCTOR CLAUDE",
    analyze = "ANALYSE",
    listening = "J'ÉCOUTE…",
    statusHigh = "ÉLEVÉ",
    statusLow = "BAS",
    statusInRange = "DANS LA CIBLE",
    loginSubtitle = "Connectez votre compte LibreLinkUp",
    emailLabel = "Email LibreLinkUp",
    passwordLabel = "Mot de passe",
    connect = "Se connecter",
    howItWorks = "Comment ça marche",
    howItWorksBody = "Utilisez votre compte LibreLinkUp (app suiveur Abbott). Le porteur du capteur doit utiliser LibreLink (app patient) et avoir partagé son flux avec ce compte. Données toutes les minutes via le cloud Abbott — pas de NFC, pas d'app tierce.",
    trendFallingFast = "Chute rapide",
    trendFalling = "Baisse",
    trendStable = "Stable",
    trendRising = "Hausse",
    trendRisingFast = "Montée rapide",
    trendStuckHigh = "reste haut",
    trendStuckLow = "reste bas",
    tabGlucose = "Glycémie",
    tabMeals = "Repas",
    tabProfile = "Profil",
    profileTitle = "PROFIL",
    profileIntro = "Donne l'essentiel — Dr Claude estime tes réglages d'insuline (à valider avec le médecin).",
    fieldNickname = "Surnom",
    fieldAge = "Âge",
    fieldWeight = "Poids (kg)",
    fieldDxYears = "Diabétique depuis (années)",
    fieldRapidName = "Insuline rapide (nom)",
    fieldRapidUnits = "Rapide u/jour",
    fieldBasalName = "Insuline lente (nom)",
    fieldBasalUnits = "Lente u/jour",
    fieldNotes = "Notes (allergies, sport…)",
    saveProfile = "ENREGISTRER",
    autoSaving = "Enregistrement…",
    profileSaved = "Profil enregistré",
    ratiosEstimated = "Réglages estimés par Dr Claude (à valider avec le médecin)",
    ratiosDoctor = "Réglages donnés par ton médecin",
    foodTitle = "REPAS",
    foodSoon = "Page repas en préparation.",
    foodDescHint = "Qu'a-t-il mangé / va manger ?",
    foodCarbsHint = "Glucides (g) — laisse vide, l'IA estime",
    foodQtyHint = "Quantité (× combien de fois)",
    foodQtyTotal = "= %1\$d g au total",
    foodAdd = "AJOUTER",
    foodVoiceHint = "Astuce : depuis Glycémie, touche le micro et dis « je vais boire un coca » — Dr Claude l'ajoute ici et estime la dose.",
    foodEmpty = "Aucun repas pour l'instant.",
    foodPlanned = "prévu",
    foodEaten = "mangé",
    foodDelete = "Supprimer",
    foodDeleteConfirm = "Supprimer ce repas ?",
    foodScan = "SCAN PRODUIT",
    foodScanning = "Analyse de la photo…",
    foodScanFail = "Photo illisible, réessaie.",
    seeAllHistory = "VOIR TOUT L'HISTORIQUE",
    filterAll = "Tout",
    historyScreenTitle = "HISTORIQUE",
    generalTab = "GÉNÉRAL",
    pastAnalyses = "ANALYSES",
    injections = "INJECTIONS",
    historyEmpty = "Rien à afficher pour l'instant.",
    back = "Retour",
    alertLow = "GLYCÉMIE BASSE",
    alertHigh = "GLYCÉMIE HAUTE",
    alertRapidRise = "MONTÉE RAPIDE",
    alertRapidFall = "CHUTE RAPIDE",
    alertActLow = "Prends du sucre maintenant.",
    alertActLowWait = "Tu as déjà pris du sucre — laisse-le agir et recontrôle.",
    alertActHigh = "Dr Claude regarde s'il faut corriger.",
    alertActFall = "Garde du sucre à portée et surveille.",
    alertActRise = "Surveille la montée.",
    remindersLabel = "Rappels repas (toutes les 4 h)",
    remindersSub = "Entre 8h et 20h",
    alarmLabel = "Alarme sonore (hypo / hyper)",
    alarmSub = "Sonne sur le téléphone en cas d'alerte. La bannière reste si tu la coupes.",
    notifCardTitle = "Notifications & alarmes",
    notifCardSub = "Volume, vibreur, heures calmes, types d'alertes",
    notifPageTitle = "Notifications & alarmes",
    notifModeTitle = "Son & vibration",
    notifModeSound = "Son + vibration",
    notifModeVibrate = "Vibreur",
    notifModeSilent = "Silencieux",
    notifVolumeLabel = "Volume de l'alarme",
    notifTestBtn = "Tester l'alarme",
    notifQuietTitle = "Heures calmes (école / nuit)",
    notifQuietLabel = "Activer les heures calmes",
    notifQuietSub = "Pendant cette plage, l'hyper vibre sans sonner. L'hypo, elle, continue de sonner (réglable ci-dessous). Le parent reçoit aussi l'alerte Telegram.",
    notifQuietFrom = "De",
    notifQuietTo = "à",
    notifTypesTitle = "Types d'alertes",
    notifHyperLabel = "Glycémie haute (hyper)",
    notifHyperSub = "Alerte au-dessus de 180 mg/dL",
    notifHypoLabel = "Glycémie basse (hypo)",
    notifHypoSub = "Alerte en dessous de 70 mg/dL",
    notifHypoWarn = "⚠️ Couper l'alarme d'hypo est risqué — ne le fais que si tu surveilles autrement.",
    notifHypoAlwaysLabel = "Hypo sonne quand même",
    notifHypoAlwaysSub = "Une glycémie basse sonne même pendant les heures calmes (recommandé pour un enfant).",
    notifHypoVibrateActive = "⚠️ L'hypo ne sonnera pas pendant les heures calmes (vibreur seul). Le parent garde l'alerte Telegram.",
    notifHypoVibrateTitle = "Mettre l'hypo en vibreur la nuit ?",
    notifHypoVibrateBody = "Pendant les heures calmes, une hypo (glycémie basse) ne sonnera plus — elle vibrera seulement. Pour un enfant, le son réveille mieux. Le parent reçoit toujours l'alerte Telegram. Continuer ?",
    notifHypoVibrateConfirm = "Mettre en vibreur",
    notifFallLabel = "Chute rapide",
    notifFallSub = "La glycémie descend vite",
    notifTelegramNote = "Le parent reçoit aussi une alerte Telegram, indépendante du téléphone et de ces réglages.",
    alertStop = "ARRÊTER L'ALARME",
    signalLost = "Signal perdu — dernière mesure il y a",
    noSignal = "NO SIGNAL",
    noSignalSub = "Aucun signal du capteur. Reconnecte-le (rapproche le téléphone qui le scanne, re-scanne). S'il ne revient pas, fais un test au doigt — ne te fie pas au dernier chiffre.",
    graphHidden = "Graphe masqué — pas de mesure récente.",
    noSignalShort = "Pas de signal",
    accountsTitle = "COMPTES",
    accountsSub = "Chaque compte suit une personne. Les données restent séparées.",
    addAccount = "AJOUTER UN COMPTE",
    accountActive = "Actif",
    removeAccountConfirm = "Retirer ce compte de l'appareil ?",
    yourProfiles = "VOS PROFILS",
    addAccountTitle = "Ajouter un compte",
    cancel = "Annuler",
    consentTitle = "À lire avant de commencer",
    consentBody = "Dr Claude est un assistant, pas un dispositif médical, et il peut se tromper.\n\nSes conseils — doses d'insuline, resucrage, analyses — sont des ESTIMATIONS, à vérifier avec ton lecteur de glycémie et, en cas de doute, ton médecin.\n\nNe suis jamais un conseil aveuglément : recoupe-le avec ton ressenti. Pour tout changement important (doses, ratios), parle-en à un professionnel de santé.\n\nC'est toi qui gardes le dernier mot sur ton traitement, et tu en restes responsable.",
    consentCheck = "J'ai lu et compris : Dr Claude n'est pas un médecin et peut se tromper.",
    consentAccept = "J'AI COMPRIS ET J'ACCEPTE",
    doseDisclaimer = "Estimation à vérifier avec ton lecteur et ton médecin — ne suis pas l'IA aveuglément.",
    safetyTitle = "Petit rappel de sécurité",
    safetyBody = "Dr Claude t'aide, mais il peut se tromper. Recoupe toujours ses conseils avec ton lecteur de glycémie et ton ressenti. Pour tout changement important de doses ou de ratios, parle-en à ton médecin. Tu gardes le dernier mot.",
    safetyOk = "COMPRIS",
    voiceLabel = "Voix de Dr Claude",
    voiceSub = "Lecture audio des analyses et réponses",
    statsPeriod = "DERNIÈRES 24 H",
    online = "En ligne",
    offline = "Hors ligne",
    charging = "en charge",
    predictTitle = "ANTICIPATION",
    predictHighSoon = "Hyper en approche (~%d mg/dL dans ~%d min). Prépare une correction une fois au-dessus de 180.",
    predictWatchFall = "La glycémie descend — garde du sucre à portée et surveille. Pas besoin d'en prendre tant que tu n'es pas en hypo.",
    predictWatchRise = "La glycémie monte — garde un œil sur la montée.",
    mealNudgeText = "Ça monte sans repas enregistré — pense à logger ton repas pour une dose précise.",
    mealNudgeLog = "LOGGER LE REPAS",
    byokTitle = "Clé IA (gratuite)",
    byokSub = "Colle ta clé Google Gemini : l'IA tourne sur TON quota gratuit. Vide = mode Hosted.",
    byokHint = "Clé Gemini",
    byokHelp = "Gratuit sur aistudio.google.com → « Create API key ». Elle reste sur ton appareil.",
    byokSaved = "Clé enregistrée",
    nativeVoiceLabel = "Voix gratuite (appareil)",
    nativeVoiceSub = "Voix Android hors-ligne. Décoche pour la voix premium (Hosted).",
    autotuneTitle = "AMÉLIORER LES RÉGLAGES",
    autotuneSub = "Dr Claude regarde tes injections des derniers jours et propose des réglages plus justes. À valider avec le médecin.",
    autotuneBtn = "PROPOSER UN RÉGLAGE",
    autotuneApply = "UTILISER CES RÉGLAGES",
    donateTitle = "Soutenir le projet",
    donateSub = "Dr Claude est gratuit et open-source. Un don aide à le maintenir.",
    donateBtn = "FAIRE UN DON",
    hostedTitle = "Mode Hosted",
    hostedSub = "Nos clés + voix premium + synchro cloud. Abonnement — à activer.",
    googleTitle = "Connexion Google",
    googleSub = "Identité seulement (≠ clé Gemini).",
    googleBtn = "SE CONNECTER AVEC GOOGLE",
    comingSoon = "Bientôt disponible",
    healthTitle = "Health Connect",
    healthSub = "Fréquence cardiaque + pas (nécessite un bracelet/une montre).",
    healthConnect = "AUTORISER L'ACCÈS",
    healthInstall = "INSTALLER HEALTH CONNECT",
    healthUnavailable = "L'app « Health Connect » (de Google/Android) n'est pas installée ou activée. Installe-la, ouvre Samsung Health comme source de données, puis reviens autoriser Dr Claude.",
    healthHr = "FC",
    healthSteps = "Pas",
    onDeviceData = "%d mesures gardées sur l'appareil",
    tabInsulin = "Insuline",
    insulinTitle = "INSULINE",
    insulinIntro = "Note ici chaque piqûre d'insuline rapide. Comme ça, Dr Claude sait combien d'insuline agit encore en toi et ne t'en propose pas trop.",
    insulinUnitsHint = "Unités (u)",
    insulinNameHint = "Insuline (nom)",
    insulinActive = "Insuline encore active",
    insulinActiveExplain = "C'est l'insuline rapide de tes dernières piqûres qui agit encore (elle met environ 4 h à disparaître). Dr Claude l'enlève de ses calculs pour ne pas te proposer une dose en trop.",
    insulinEmpty = "Aucune injection enregistrée pour l'instant.",
    insulinLogged = "Injection enregistrée",
    saveFailed = "Échec de l'enregistrement — réessaie (rien n'a été enregistré).",
    serviceDownReach = "⚠️ Service Dr Claude injoignable — historique, stats et analyses indisponibles. Ta glycémie et les alarmes fonctionnent toujours.",
    serviceDownCredits = "⚠️ IA indisponible : plus de crédits / quota atteint. Le suivi glycémie et les alarmes continuent.",
    serviceDownRate = "⚠️ IA saturée (trop de requêtes) — réessaie dans un instant.",
    // Never tells a Hosted user to "activate Hosted mode" — they already did, and reading that when
    // the real fault is a server-side key is what made the scan look like a settings problem.
    serviceDownAuth = "⚠️ L'IA ne répond pas : clé refusée (côté serveur, ou ta clé perso si tu en as mis une). Glycémies et alarmes non affectées.",
    serviceDownAi = "⚠️ IA indisponible pour le moment. Le suivi glycémie et les alarmes continuent.",
    tugTitle = "QUI MÈNE LA COURSE ?",
    tugSugarWins = "🍬 Le sucre mène — ça pousse vers le haut",
    tugInsulinWins = "💉 L'insuline mène — ça pousse vers le bas",
    tugTie = "🤝 Au coude-à-coude — plutôt stable",
    tugNeutral = "Rien d'actif pour l'instant 😴",
    tugDisclaimer = "Estimation visuelle (insuline active vs sucres en digestion) — pas un conseil de dose.",
    tugActionSugar = "À surveiller : la glycémie a tendance à monter — recontrôle bientôt.",
    tugActionInsulin = "À surveiller : la glycémie a tendance à baisser — garde du sucre à portée et recontrôle.",
    tugActionTie = "Plutôt équilibré — recontrôle dans un moment.",
    insulinRecent = "INJECTIONS RÉCENTES",
    whenLabel = "Quand ?",
    whenNow = "Maintenant",
    whenTitle = "Quand l'as-tu pris ?",
    whenToday = "Aujourd'hui",
    whenYesterday = "Hier",
    editTitle = "Modifier",
    editSave = "MODIFIER",
    profTabProfile = "PROFIL",
    profTabNotifs = "NOTIFS",
    profTabSettings = "RÉGLAGES",
    deleteEntry = "Supprimer",
    insulinSettingsTitle = "TES RÉGLAGES D'INSULINE",
    insulinSettingsCarb = "Pour 1 unité d'insuline : environ %d g de glucides (≈ %d sucres).",
    insulinSettingsCorr = "1 unité fait baisser la glycémie d'environ %d mg/dL.",
    insulinSettingsTarget = "Glycémie visée : %d mg/dL.",
    insulinSettingsNone = "Pas encore de réglages. Remplis-les dans l'onglet Profil, ou laisse Dr Claude les estimer.",
    aiNeedsKey = "Pour utiliser l'IA : active le mode Hosted ou ajoute ta clé Gemini gratuite (onglet Profil).",
    aiError = "L'analyse n'a pas abouti (délai dépassé) — réessaie.",
    healthUseLabel = "Utiliser Health Connect",
    healthUseSub = "Lit ta fréquence cardiaque et tes pas via l'app « Health Connect » (Google/Android), elle-même alimentée par Samsung Health ou ta montre. La fréquence cardiaque nécessite un bracelet/une montre connectée. Entièrement optionnel.",
    healthManage = "GÉRER DANS HEALTH CONNECT",
    clearDataTitle = "Données locales",
    clearDataSub = "Efface l'historique de glycémie gardé sur cet appareil (n'efface pas le cloud).",
    clearDataBtn = "EFFACER LES DONNÉES LOCALES",
    clearDataDone = "Données locales effacées",
    fieldCarbRatio = "Ratio glucides (1 u / X g)",
    fieldCorrection = "Correction (1 u / X mg/dL)",
    fieldTarget = "Cible (mg/dL)",
    ratiosOptional = "Réglages du médecin (optionnel — sinon estimés)",
    scanGallery = "CHOISIR UNE PHOTO",
    replayVoice = "Réécouter",
    stopVoice = "Couper",
    ratioVisualTitle = "CE QU'UNE UNITÉ D'INSULINE COUVRE",
    ratioVisualUnit = "1 unité d'insuline",
    ratioVisualCubes = "≈ %d sucres",
    ratioVisualGrams = "~%d g de glucides",
    ratioApplied = "Nouveau réglage appliqué ✓",
    healthOpenApp = "Rien ne s'ouvre ? Ouvre Health Connect",
    ratioCurrentVsProposed = "Actuel : 1 u = %1\$d g  →  proposé : 1 u = %2\$d g",
    foodAddTitle = "Ajouter un repas",
    insulinAddTitle = "Ajouter une dose",
    insulinTabDoses = "INJECTIONS",
    insulinTabSettings = "RÉGLAGES",
    foodScanShort = "SCANNER",
    foodGalleryShort = "GALERIE",
    insulinRapidTag = "Rapide",
    insulinSlowTag = "Lente",
)

val StringsEs = Strings(
    sensor = "Sensor FreeStyle",
    current = "ACTUAL",
    updated = "ACT",
    waiting = "Esperando mediciones…",
    average = "PROMEDIO",
    target = "OBJETIVO",
    statHigh = "% ALTO",
    statLow = "% BAJO",
    periodLast24h = "ÚLTIMAS 24 H",
    periodOverDays = "ÚLTIMOS %d DÍAS",
    periodOnDay = "EL %s",
    periodFromTo = "DEL %1\$s AL %2\$s",
    deviation = "DESVÍO",
    history = "HISTORIAL",
    talkToMom = "HABLAR",
    momTitle = "DOCTOR CLAUDE",
    analyze = "ANÁLISIS",
    listening = "TE ESCUCHO…",
    statusHigh = "ALTO",
    statusLow = "BAJO",
    statusInRange = "EN OBJETIVO",
    loginSubtitle = "Conecta tu cuenta LibreLinkUp",
    emailLabel = "Email LibreLinkUp",
    passwordLabel = "Contraseña",
    connect = "Conectar",
    howItWorks = "Cómo funciona",
    howItWorksBody = "Usa tu cuenta LibreLinkUp (app seguidor de Abbott). El portador del sensor debe usar LibreLink (app paciente) y haber compartido sus datos con esta cuenta. Datos cada minuto vía la nube de Abbott — sin NFC, sin apps de terceros.",
    trendFallingFast = "Bajada rápida",
    trendFalling = "Bajando",
    trendStable = "Estable",
    trendRising = "Subiendo",
    trendRisingFast = "Subida rápida",
    trendStuckHigh = "sigue alto",
    trendStuckLow = "sigue bajo",
    tabGlucose = "Glucosa",
    tabMeals = "Comidas",
    tabProfile = "Perfil",
    profileTitle = "PERFIL",
    profileIntro = "Da lo esencial — Dr Claude estima tus ajustes de insulina (a validar con el médico).",
    fieldNickname = "Apodo",
    fieldAge = "Edad",
    fieldWeight = "Peso (kg)",
    fieldDxYears = "Diabético desde (años)",
    fieldRapidName = "Insulina rápida (nombre)",
    fieldRapidUnits = "Rápida u/día",
    fieldBasalName = "Insulina lenta (nombre)",
    fieldBasalUnits = "Lenta u/día",
    fieldNotes = "Notas (alergias, deporte…)",
    saveProfile = "GUARDAR",
    autoSaving = "Guardando…",
    profileSaved = "Perfil guardado",
    ratiosEstimated = "Ajustes estimados por Dr Claude (a validar con el médico)",
    ratiosDoctor = "Ajustes dados por tu médico",
    foodTitle = "COMIDAS",
    foodSoon = "Página de comidas en preparación.",
    foodDescHint = "¿Qué comió / va a comer?",
    foodCarbsHint = "Carbos (g) — déjalo vacío, la IA estima",
    foodQtyHint = "Cantidad (× cuántas veces)",
    foodQtyTotal = "= %1\$d g en total",
    foodAdd = "AÑADIR",
    foodVoiceHint = "Truco: desde Glucosa, toca el micrófono y di « voy a beber una Coca » — Dr Claude lo añade aquí y estima la dosis.",
    foodEmpty = "Sin comidas por ahora.",
    foodPlanned = "previsto",
    foodEaten = "comido",
    foodDelete = "Eliminar",
    foodDeleteConfirm = "¿Eliminar esta comida?",
    foodScan = "ESCANEAR PRODUCTO",
    foodScanning = "Analizando la foto…",
    foodScanFail = "Foto ilegible, reinténtalo.",
    seeAllHistory = "VER TODO EL HISTORIAL",
    filterAll = "Todo",
    historyScreenTitle = "HISTORIAL",
    generalTab = "GENERAL",
    pastAnalyses = "ANÁLISIS",
    injections = "INYECCIONES",
    historyEmpty = "Nada que mostrar por ahora.",
    back = "Volver",
    alertLow = "GLUCOSA BAJA",
    alertHigh = "GLUCOSA ALTA",
    alertRapidRise = "SUBIDA RÁPIDA",
    alertRapidFall = "BAJADA RÁPIDA",
    alertActLow = "Toma azúcar ahora.",
    alertActLowWait = "Ya tomaste azúcar — deja que actúe y vuelve a medir.",
    alertActHigh = "Dr Claude mira si hay que corregir.",
    alertActFall = "Ten azúcar a mano y vigila.",
    alertActRise = "Vigila la subida.",
    remindersLabel = "Recordatorios de comida (cada 4 h)",
    remindersSub = "Entre las 8 y las 20h",
    alarmLabel = "Alarma sonora (hipo / hiper)",
    alarmSub = "Suena en el teléfono al alertar. El aviso visual sigue si la silencias.",
    notifCardTitle = "Notificaciones y alarmas",
    notifCardSub = "Volumen, vibración, horas tranquilas, tipos de alerta",
    notifPageTitle = "Notificaciones y alarmas",
    notifModeTitle = "Sonido y vibración",
    notifModeSound = "Sonido + vibración",
    notifModeVibrate = "Vibración",
    notifModeSilent = "Silencio",
    notifVolumeLabel = "Volumen de la alarma",
    notifTestBtn = "Probar la alarma",
    notifQuietTitle = "Horas tranquilas (escuela / noche)",
    notifQuietLabel = "Activar horas tranquilas",
    notifQuietSub = "Durante este intervalo, la hiper vibra sin sonar. La hipo, en cambio, sigue sonando (ajustable abajo). El padre también recibe la alerta de Telegram.",
    notifQuietFrom = "De",
    notifQuietTo = "a",
    notifTypesTitle = "Tipos de alerta",
    notifHyperLabel = "Glucosa alta (hiper)",
    notifHyperSub = "Avisa por encima de 180 mg/dL",
    notifHypoLabel = "Glucosa baja (hipo)",
    notifHypoSub = "Avisa por debajo de 70 mg/dL",
    notifHypoWarn = "⚠️ Apagar la alarma de hipo es arriesgado — solo si vigilas de otra forma.",
    notifHypoAlwaysLabel = "La hipo suena igualmente",
    notifHypoAlwaysSub = "Una glucosa baja suena incluso durante las horas tranquilas (recomendado para un niño).",
    notifHypoVibrateActive = "⚠️ La hipo no sonará durante las horas tranquilas (solo vibra). El padre mantiene la alerta de Telegram.",
    notifHypoVibrateTitle = "¿Poner la hipo en vibración por la noche?",
    notifHypoVibrateBody = "Durante las horas tranquilas, una hipo (glucosa baja) ya no sonará — solo vibrará. Para un niño, el sonido despierta mejor. El padre sigue recibiendo la alerta de Telegram. ¿Continuar?",
    notifHypoVibrateConfirm = "Poner en vibración",
    notifFallLabel = "Bajada rápida",
    notifFallSub = "La glucosa baja rápido",
    notifTelegramNote = "El padre también recibe una alerta de Telegram, independiente del teléfono y de estos ajustes.",
    alertStop = "DETENER LA ALARMA",
    signalLost = "Señal perdida — última medición hace",
    noSignal = "NO SIGNAL",
    noSignalSub = "Sin señal del sensor. Reconéctalo (acerca el teléfono que lo escanea, vuelve a escanear). Si no vuelve, hazte una prueba de dedo — no te fíes del último número.",
    graphHidden = "Gráfico oculto — sin medición reciente.",
    noSignalShort = "Sin señal",
    accountsTitle = "CUENTAS",
    accountsSub = "Cada cuenta sigue a una persona. Los datos quedan separados.",
    addAccount = "AÑADIR UNA CUENTA",
    accountActive = "Activo",
    removeAccountConfirm = "¿Quitar esta cuenta del dispositivo?",
    yourProfiles = "TUS PERFILES",
    addAccountTitle = "Añadir una cuenta",
    cancel = "Cancelar",
    consentTitle = "Léelo antes de empezar",
    consentBody = "Dr Claude es un asistente, no un dispositivo médico, y puede equivocarse.\n\nSus consejos — dosis de insulina, azúcar, análisis — son ESTIMACIONES, a verificar con tu medidor de glucosa y, en caso de duda, tu médico.\n\nNunca sigas un consejo a ciegas: contrástalo con cómo te sientes. Para cualquier cambio importante (dosis, ratios), háblalo con un profesional de salud.\n\nTú tienes la última palabra sobre tu tratamiento, y sigues siendo responsable.",
    consentCheck = "He leído y entendido: Dr Claude no es un médico y puede equivocarse.",
    consentAccept = "ENTIENDO Y ACEPTO",
    doseDisclaimer = "Estimación a verificar con tu medidor y tu médico — no sigas a la IA a ciegas.",
    safetyTitle = "Pequeño recordatorio de seguridad",
    safetyBody = "Dr Claude te ayuda, pero puede equivocarse. Contrasta siempre sus consejos con tu medidor de glucosa y cómo te sientes. Para cualquier cambio importante de dosis o ratios, háblalo con tu médico. Tú tienes la última palabra.",
    safetyOk = "ENTENDIDO",
    voiceLabel = "Voz de Dr Claude",
    voiceSub = "Lectura en voz alta de los análisis y respuestas",
    statsPeriod = "ÚLTIMAS 24 H",
    online = "En línea",
    offline = "Sin conexión",
    charging = "cargando",
    predictTitle = "ANTICIPACIÓN",
    predictHighSoon = "Hiper en aproximación (~%d mg/dL en ~%d min). Prepárate para corregir tras pasar de 180.",
    predictWatchFall = "La glucosa baja — ten azúcar a mano y vigila. No hace falta tomarlo mientras no estés en hipo.",
    predictWatchRise = "La glucosa sube — vigila la subida.",
    mealNudgeText = "Sube sin comida registrada — registra tu comida para una dosis precisa.",
    mealNudgeLog = "REGISTRAR COMIDA",
    byokTitle = "Clave IA (gratis)",
    byokSub = "Pega tu clave Google Gemini: la IA usa TU cuota gratis. Vacío = modo Hosted.",
    byokHint = "Clave Gemini",
    byokHelp = "Gratis en aistudio.google.com → « Create API key ». Se queda en tu dispositivo.",
    byokSaved = "Clave guardada",
    nativeVoiceLabel = "Voz gratis (dispositivo)",
    nativeVoiceSub = "Voz Android sin conexión. Desmarca para la voz premium (Hosted).",
    autotuneTitle = "MEJORAR LOS AJUSTES",
    autotuneSub = "Dr Claude mira tus inyecciones de los últimos días y propone ajustes más precisos. A validar con el médico.",
    autotuneBtn = "PROPONER UN AJUSTE",
    autotuneApply = "USAR ESTOS AJUSTES",
    donateTitle = "Apoyar el proyecto",
    donateSub = "Dr Claude es gratis y de código abierto. Una donación ayuda a mantenerlo.",
    donateBtn = "DONAR",
    hostedTitle = "Modo Hosted",
    hostedSub = "Nuestras claves + voz premium + sync en la nube. Suscripción — por activar.",
    googleTitle = "Inicio con Google",
    googleSub = "Solo identidad (≠ clave Gemini).",
    googleBtn = "ENTRAR CON GOOGLE",
    comingSoon = "Próximamente",
    healthTitle = "Health Connect",
    healthSub = "Frecuencia cardíaca + pasos (necesita un wearable).",
    healthConnect = "AUTORIZAR EL ACCESO",
    healthInstall = "INSTALAR HEALTH CONNECT",
    healthUnavailable = "La app « Health Connect » (de Google/Android) no está instalada o activada. Instálala, abre Samsung Health como fuente de datos y vuelve a autorizar a Dr Claude.",
    healthHr = "FC",
    healthSteps = "Pasos",
    onDeviceData = "%d mediciones guardadas en el dispositivo",
    tabInsulin = "Insulina",
    insulinTitle = "INSULINA",
    insulinIntro = "Anota aquí cada pinchazo de insulina rápida. Así Dr Claude sabe cuánta insulina sigue actuando en ti y no te propone de más.",
    insulinUnitsHint = "Unidades (u)",
    insulinNameHint = "Insulina (nombre)",
    insulinActive = "Insulina aún activa",
    insulinActiveExplain = "Es la insulina rápida de tus últimos pinchazos que sigue actuando (tarda unas 4 h en irse). Dr Claude la resta de sus cálculos para no proponerte una dosis de más.",
    insulinEmpty = "Sin inyecciones registradas por ahora.",
    insulinLogged = "Inyección guardada",
    saveFailed = "No se pudo guardar — vuelve a intentarlo (no se registró nada).",
    serviceDownReach = "⚠️ Servicio Dr Claude no disponible — historial, estadísticas y análisis no disponibles. Tu glucosa y las alarmas siguen funcionando.",
    serviceDownCredits = "⚠️ IA no disponible: sin créditos / cuota agotada. El seguimiento de glucosa y las alarmas continúan.",
    serviceDownRate = "⚠️ IA saturada (demasiadas peticiones) — reinténtalo en un momento.",
    serviceDownAuth = "⚠️ La IA no responde: clave rechazada (en el servidor, o tu clave propia si has puesto una). Glucosa y alarmas no afectadas.",
    serviceDownAi = "⚠️ IA no disponible ahora mismo. El seguimiento de glucosa y las alarmas continúan.",
    tugTitle = "¿QUIÉN VA GANANDO?",
    tugSugarWins = "🍬 Gana el azúcar — empuja hacia arriba",
    tugInsulinWins = "💉 Gana la insulina — empuja hacia abajo",
    tugTie = "🤝 Muy igualado — más bien estable",
    tugNeutral = "Nada activo por ahora 😴",
    tugDisclaimer = "Estimación visual (insulina activa vs azúcares digiriéndose) — no es un consejo de dosis.",
    tugActionSugar = "A vigilar: la glucosa tiende a subir — vuelve a medir pronto.",
    tugActionInsulin = "A vigilar: la glucosa tiende a bajar — ten azúcar a mano y vuelve a medir.",
    tugActionTie = "Bastante equilibrado — vuelve a medir en un rato.",
    insulinRecent = "INYECCIONES RECIENTES",
    whenLabel = "¿Cuándo?",
    whenNow = "Ahora",
    whenTitle = "¿Cuándo lo tomaste?",
    whenToday = "Hoy",
    whenYesterday = "Ayer",
    editTitle = "Editar",
    editSave = "MODIFICAR",
    profTabProfile = "PERFIL",
    profTabNotifs = "ALERTAS",
    profTabSettings = "AJUSTES",
    deleteEntry = "Eliminar",
    insulinSettingsTitle = "TUS AJUSTES DE INSULINA",
    insulinSettingsCarb = "Por 1 unidad de insulina: unos %d g de carbohidratos (≈ %d terrones).",
    insulinSettingsCorr = "1 unidad baja la glucosa unos %d mg/dL.",
    insulinSettingsTarget = "Glucosa objetivo: %d mg/dL.",
    insulinSettingsNone = "Aún no hay ajustes. Rellénalos en la pestaña Perfil, o deja que Dr Claude los estime.",
    aiNeedsKey = "Para usar la IA: activa el modo Hosted o añade tu clave Gemini gratis (pestaña Perfil).",
    aiError = "El análisis no se completó (tiempo agotado) — inténtalo de nuevo.",
    healthUseLabel = "Usar Health Connect",
    healthUseSub = "Lee tu frecuencia cardíaca y tus pasos mediante la app « Health Connect » (Google/Android), alimentada por Samsung Health o tu reloj. La frecuencia cardíaca necesita una pulsera/un reloj. Totalmente opcional.",
    healthManage = "GESTIONAR EN HEALTH CONNECT",
    clearDataTitle = "Datos locales",
    clearDataSub = "Borra el historial de glucosa guardado en este dispositivo (no borra la nube).",
    clearDataBtn = "BORRAR DATOS LOCALES",
    clearDataDone = "Datos locales borrados",
    fieldCarbRatio = "Ratio carbos (1 u / X g)",
    fieldCorrection = "Corrección (1 u / X mg/dL)",
    fieldTarget = "Objetivo (mg/dL)",
    ratiosOptional = "Ajustes del médico (opcional — si no, estimados)",
    scanGallery = "ELEGIR UNA FOTO",
    replayVoice = "Volver a escuchar",
    stopVoice = "Detener",
    ratioVisualTitle = "LO QUE CUBRE UNA UNIDAD DE INSULINA",
    ratioVisualUnit = "1 unidad de insulina",
    ratioVisualCubes = "≈ %d terrones",
    ratioVisualGrams = "~%d g de carbohidratos",
    ratioApplied = "Nuevo ajuste aplicado ✓",
    healthOpenApp = "¿No se abre nada? Abre Health Connect",
    ratioCurrentVsProposed = "Actual: 1 u = %1\$d g  →  propuesto: 1 u = %2\$d g",
    foodAddTitle = "Añadir una comida",
    insulinAddTitle = "Añadir una dosis",
    insulinTabDoses = "INYECCIONES",
    insulinTabSettings = "AJUSTES",
    foodScanShort = "ESCANEAR",
    foodGalleryShort = "GALERÍA",
    insulinRapidTag = "Rápida",
    insulinSlowTag = "Lenta",
)

fun stringsFor(lang: Lang): Strings = if (lang == Lang.ES) StringsEs else StringsFr

val LocalStrings = compositionLocalOf { StringsFr }

/**
 * Background/standby-monitoring strings, kept in a SEPARATE small holder on purpose: the main
 * [Strings] data class sits right at the Dalvik invoke-range ceiling (a constructor invocation is
 * limited to 256 registers = ~255 args), so adding fields to it makes the whole class fail ART
 * verification at load (VerifyError in <clinit>). New string groups go here, not into [Strings].
 */
data class BgStrings(
    val bgTitle: String,
    val bgBody: String,
    val bgCardSub: String,
    val bgButton: String,
    val bgLater: String,
    val bgActive: String,
    // Carte « analyse périmée » sur l'accueil (>20 min). %s = heure de l'ancienne analyse.
    val analysisStaleTitle: String,
    val analysisStaleBody: String,
    // Bannière globale « réseau perdu » (pas de Wi-Fi ni de données mobiles).
    val networkLost: String,
    // HbA1c sur la page Profil : champ « dernier labo » + estimation maison (GMI) calculée
    // depuis la glycémie moyenne. %1$d = moyenne mg/dL, %2$d = nb de jours de mesures.
    val hba1cField: String,
    val fieldCountry: String,
    val carbFromLabel: String,
    val carbFromDb: String,
    val carbFromDbNamed: String,
    val carbFromEstimate: String,
    val gmiTitle: String,
    val gmiExplain: String,
    val gmiAccumulating: String,
    val gmiPending: String,
    // « Quand ? » : 3e puce jour pour planifier une dose/un repas DANS LE FUTUR.
    val whenTomorrow: String,
    // Étiquette d'une dose d'insuline datée dans le futur (pas encore faite — exclue de l'IOB).
    val dosePlanned: String,
    // Carte rouge quand le capteur a dépassé ses 14 jours (remplace le NO SIGNAL générique).
    val sensorExpiredTitle: String,
    val sensorExpiredSub: String,
    // Zones ORANGE « presque bas / presque haut » (60-69 et 171-180) : affichées, jamais sonores.
    val alertNearLow: String,
    val alertNearHigh: String,
    val alertActNearLow: String,
    val alertActNearHigh: String,
    // Bandeau global « un audio est en train d'être lu », avec son bouton d'arrêt.
    val audioPlaying: String,
    val audioStop: String,
    // « Sucre encore actif » (glucides en cours d'absorption) sur la page Repas.
    // carbsActiveValue : %1$d = grammes, %2$d = équivalent sucres. carbsActiveRow : %d = grammes.
    val carbsActiveTitle: String,
    val carbsActiveValue: String,
    val carbsActiveExplain: String,
    val carbsActiveRow: String,
)

private val BgStringsFr = BgStrings(
    bgTitle = "Suivi en veille",
    bgBody = "Pour que la glycémie continue d'être lue et que l'alarme sonne même écran éteint, autorise Dr Claude à fonctionner en arrière-plan. Sans ça, le téléphone (surtout Samsung) met l'app en veille et le suivi ne reprend qu'au déverrouillage.",
    bgCardSub = "Le téléphone peut suspendre l'app en veille. Autorise l'arrière-plan pour un suivi continu, écran éteint.",
    bgButton = "Autoriser l'arrière-plan",
    bgLater = "Plus tard",
    bgActive = "✓ Autorisé — la glycémie est suivie même écran éteint.",
    analysisStaleTitle = "ANALYSE À RAFRAÎCHIR",
    analysisStaleBody = "Ce bilan date de %s — la glycémie a bougé depuis. Appuie pour une nouvelle analyse.",
    networkLost = "Réseau perdu — sans Wi-Fi ni données mobiles, Dr Claude est limité : pas de nouvelle glycémie, ni analyse ni sauvegarde. Tout reprend dès que la connexion revient.",
    hba1cField = "HbA1c — dernier labo (%)",
    fieldCountry = "Pays (pour le calcul des glucides)",
    carbFromLabel = "Glucides lus sur l'étiquette du produit.",
    carbFromDb = "Glucides issus de la base produits de ton pays.",
    carbFromDbNamed = "Glucides issus de la base produits : %s.",
    carbFromEstimate = "Glucides ESTIMÉS — vérifie sur l'emballage et corrige si besoin.",
    gmiTitle = "HbA1c ESTIMÉE (GMI)",
    gmiExplain = "Estimée à partir de ta glycémie moyenne (%1\$d mg/dL sur %2\$d jours) — c'est l'indicateur « GMI » qu'affiche aussi LibreLink. Elle complète ton analyse de labo, sans la remplacer.",
    gmiAccumulating = "Dr Claude l'estimera après environ 14 jours de mesures (%1\$d j pour l'instant). En dessous, le chiffre ne serait pas fiable — on préfère ne rien afficher de trompeur.",
    gmiPending = "Dr Claude estimera ton HbA1c (GMI) après quelques jours de mesures.",
    whenTomorrow = "Demain",
    dosePlanned = "Prévue",
    sensorExpiredTitle = "CAPTEUR EXPIRÉ",
    sensorExpiredSub = "Le capteur a atteint ses 14 jours — pose un nouveau capteur (compte ~1 h de démarrage). En attendant, mesure au doigt avant toute décision.",
    alertNearLow = "PRESQUE BAS",
    alertNearHigh = "PRESQUE HAUT",
    alertActNearLow = "Surveille — garde du sucre à portée. Pas d'alarme tant que ça reste au-dessus de 60.",
    alertActNearHigh = "Surveille — pas encore une hyper. L'alarme ne sonne qu'au-dessus de 180.",
    audioPlaying = "Lecture audio en cours",
    audioStop = "ARRÊTER",
    carbsActiveTitle = "SUCRE ENCORE ACTIF",
    carbsActiveValue = "≈ %1\$d g (≈ %2\$d sucres)",
    carbsActiveExplain = "Les glucides de tes derniers repas encore en train d'être absorbés — ils vont continuer à faire monter la glycémie. Un sucre rapide agit en ~2 h, des pâtes ou un repas gras jusqu'à ~4 h.",
    carbsActiveRow = "encore ~%d g",
)

private val BgStringsEs = BgStrings(
    bgTitle = "Vigilancia en reposo",
    bgBody = "Para que la glucosa se siga leyendo y la alarma suene aunque la pantalla esté apagada, permite que Dr Claude funcione en segundo plano. Sin esto, el teléfono (sobre todo Samsung) suspende la app y el seguimiento solo se reanuda al desbloquear.",
    bgCardSub = "El teléfono puede suspender la app en reposo. Permite el segundo plano para un seguimiento continuo con la pantalla apagada.",
    bgButton = "Permitir segundo plano",
    bgLater = "Más tarde",
    bgActive = "✓ Permitido — la glucosa se vigila incluso con la pantalla apagada.",
    analysisStaleTitle = "ANÁLISIS A ACTUALIZAR",
    analysisStaleBody = "Este informe es de las %s — la glucosa ha cambiado. Toca para un análisis nuevo.",
    networkLost = "Sin conexión — sin Wi-Fi ni datos móviles, Dr Claude está limitado: sin glucosa nueva, ni análisis ni guardado. Todo se reanuda en cuanto vuelva la conexión.",
    hba1cField = "HbA1c — último análisis (%)",
    fieldCountry = "País (para el cálculo de carbohidratos)",
    carbFromLabel = "Carbohidratos leídos en la etiqueta del producto.",
    carbFromDb = "Carbohidratos de la base de productos de tu país.",
    carbFromDbNamed = "Carbohidratos de la base de productos: %s.",
    carbFromEstimate = "Carbohidratos ESTIMADOS — compruébalo en el envase y corrige si hace falta.",
    gmiTitle = "HbA1c ESTIMADA (GMI)",
    gmiExplain = "Estimada a partir de tu glucosa media (%1\$d mg/dL en %2\$d días) — es el indicador « GMI » que muestra también LibreLink. Complementa tu análisis de laboratorio, sin sustituirlo.",
    gmiAccumulating = "Dr Claude la estimará tras unos 14 días de mediciones (%1\$d días por ahora). Con menos, el número no sería fiable — preferimos no mostrar nada engañoso.",
    gmiPending = "Dr Claude estimará tu HbA1c (GMI) tras unos días de mediciones.",
    whenTomorrow = "Mañana",
    dosePlanned = "Prevista",
    sensorExpiredTitle = "SENSOR CADUCADO",
    sensorExpiredSub = "El sensor llegó a sus 14 días — pon un sensor nuevo (cuenta ~1 h de arranque). Mientras tanto, mide en el dedo antes de cualquier decisión.",
    alertNearLow = "CASI BAJA",
    alertNearHigh = "CASI ALTA",
    alertActNearLow = "Vigila — ten azúcar a mano. No suena mientras se mantenga por encima de 60.",
    alertActNearHigh = "Vigila — todavía no es una hiper. La alarma solo suena por encima de 180.",
    audioPlaying = "Audio en reproducción",
    audioStop = "PARAR",
    carbsActiveTitle = "AZÚCAR AÚN ACTIVO",
    carbsActiveValue = "≈ %1\$d g (≈ %2\$d terrones)",
    carbsActiveExplain = "Los carbohidratos de tus últimas comidas que aún se están absorbiendo — seguirán subiendo la glucosa. Un azúcar rápido actúa en ~2 h; la pasta o una comida grasa hasta ~4 h.",
    carbsActiveRow = "aún ~%d g",
)

fun bgStringsFor(lang: Lang): BgStrings = if (lang == Lang.ES) BgStringsEs else BgStringsFr

/**
 * Strings for the device-role screen, kept OUT of [Strings] on purpose.
 *
 * [Strings] sits at 252 constructor properties and a dex `invoke-range` tops out at 255 registers
 * (254 arguments plus `this`). Adding these there would cross the ceiling and the app would refuse to
 * launch at all — the class verifier rejects LocalizationKt.<clinit> with "invalid arg count (0)",
 * which COMPILES fine and only fails on a device. Same pattern as [BgStrings] above.
 */
data class RoleStrings(
    val title: String,
    val intro: String,
    val parentTitle: String,
    val parentBody: String,
    val childTitle: String,
    val childBody: String,
    val childBodyNamed: String,
    val changeLater: String,
    val badgeTitle: String,
    val badgeParent: String,
    val badgeChild: String,
    val badgeChildNamed: String,
    val badgeParentNote: String,
    val badgeChildNote: String,
    val change: String,
    val patientsLocked: String,
    /** "Dossier affiché : %s" — WHOSE data the app is showing, named. */
    val badgeRecord: String,
    /** Same line when the followed-people list could not be read, so the person can't be named. */
    val badgeRecordUnknown: String,
    /** Shown where the patient switcher would be when the followed-people list came back empty. */
    val patientsUnavailable: String,
    /** Step 2 of "whose phone is this?": WHICH followed person this device belongs to. */
    val pickPersonTitle: String,
    val pickPersonBody: String,
    /** Final confirmation — pinning a child device cannot be undone without a reinstall. */
    val confirmTitle: String,
    val confirmBody: String,
    val confirmYes: String,
    val confirmNo: String,
    /** Replaces "Changer" on a pinned device: says why there is no way back. */
    val lockedForGood: String,
    /** Pinned device: the other people are viewable, not switchable. */
    val patientsPeek: String,
    val peekClose: String,
    val peekNote: String,
    val peekNoReading: String,
    val peekJustNow: String,
    /** %d = minutes since that person's last reading. */
    val peekMinutesAgo: String,
)

private val RoleStringsFr = RoleStrings(
    title = "À qui est ce téléphone ?",
    intro = "Un même compte peut suivre plusieurs personnes. Dire à qui appartient ce téléphone évite qu'une insuline, un repas ou une analyse vocale se retrouve sur le mauvais dossier.",
    parentTitle = "Mon téléphone (parent)",
    // NOT "ton propre dossier" : sur un téléphone parent, le dossier ouvert est celui de la personne
    // suivie (l'enfant), jamais celui du parent. La formule d'avant décrivait l'inverse de ce que
    // l'écran affichait juste en dessous.
    parentBody = "Accès à toutes les personnes suivies par le compte, et bascule de l'une à l'autre. Rien n'est verrouillé.",
    childTitle = "Le téléphone de la personne suivie",
    childBody = "Ce téléphone restera sur un seul dossier. Aucun mélange possible avec quelqu'un d'autre.",
    childBodyNamed = "Ce téléphone restera sur le dossier de %s. Aucun mélange possible avec quelqu'un d'autre.",
    changeLater = "Le choix « parent » reste modifiable dans Profil. Verrouiller ce téléphone sur une personne est en revanche DÉFINITIF.",
    badgeTitle = "CE TÉLÉPHONE",
    badgeParent = "Mon téléphone (parent)",
    badgeChild = "Téléphone de la personne suivie",
    badgeChildNamed = "Téléphone de %s",
    badgeParentNote = "Tu peux basculer entre les personnes suivies par ce compte.",
    badgeChildNote = "Verrouillé sur un seul dossier : rien ne peut partir sur celui de quelqu'un d'autre.",
    change = "Changer",
    patientsLocked = "Ce téléphone est verrouillé sur cette personne. Passe en téléphone parent pour changer.",
    badgeRecord = "Dossier affiché : %s",
    badgeRecordUnknown = "Dossier affiché : personne non identifiée — la liste des personnes suivies n'a pas pu être lue.",
    patientsUnavailable = "Liste des personnes suivies indisponible : le compte n'a pas pu être interrogé. Impossible de basculer d'une personne à l'autre tant qu'elle ne revient pas.",
    pickPersonTitle = "De qui est ce téléphone ?",
    pickPersonBody = "Choisis la personne à qui appartient ce téléphone. Tout ce qui sera enregistré ici — insuline, repas, analyses — ira sur son dossier, et uniquement sur le sien.",
    confirmTitle = "Verrouiller sur %s ?",
    confirmBody = "Ce téléphone sera définitivement lié au dossier de %s. Il n'y aura plus aucun moyen d'en changer, ni de revenir en téléphone parent : il faudrait désinstaller puis réinstaller l'application.",
    confirmYes = "Verrouiller définitivement",
    confirmNo = "Annuler",
    lockedForGood = "Verrouillage définitif : seule une réinstallation complète de l'application peut le lever.",
    patientsPeek = "Tu peux jeter un œil à la glycémie des autres personnes du compte : appuie sur un nom. C'est un simple aperçu — ton dossier reste le tien, rien ne bascule.",
    peekClose = "Fermer",
    peekNote = "Aperçu seulement. Tes repas, tes insulines et tes analyses restent sur ton dossier.",
    peekNoReading = "Pas de mesure récente pour cette personne.",
    peekJustNow = "à l'instant",
    peekMinutesAgo = "il y a %d min",
)

private val RoleStringsEs = RoleStrings(
    title = "¿De quién es este teléfono?",
    intro = "Una misma cuenta puede seguir a varias personas. Decir de quién es este teléfono evita que una insulina, una comida o un análisis de voz acabe en el historial equivocado.",
    parentTitle = "Mi teléfono (padre o madre)",
    parentBody = "Acceso a todas las personas seguidas por la cuenta, y cambio de una a otra. Nada queda bloqueado.",
    childTitle = "El teléfono de la persona seguida",
    childBody = "Este teléfono se quedará en un solo historial. Ninguna mezcla posible con otra persona.",
    childBodyNamed = "Este teléfono se quedará en el historial de %s. Ninguna mezcla posible con otra persona.",
    changeLater = "La opción « padres » se puede cambiar desde Perfil. Bloquear este teléfono en una persona es, en cambio, DEFINITIVO.",
    badgeTitle = "ESTE TELÉFONO",
    badgeParent = "Mi teléfono (padre o madre)",
    badgeChild = "Teléfono de la persona seguida",
    badgeChildNamed = "Teléfono de %s",
    badgeParentNote = "Puedes cambiar entre las personas seguidas por esta cuenta.",
    badgeChildNote = "Bloqueado en un solo historial: nada puede acabar en el de otra persona.",
    change = "Cambiar",
    patientsLocked = "Este teléfono está bloqueado en esta persona. Cambia a teléfono de padre para poder cambiarla.",
    badgeRecord = "Historial mostrado: %s",
    badgeRecordUnknown = "Historial mostrado: persona no identificada — no se ha podido leer la lista de personas seguidas.",
    patientsUnavailable = "Lista de personas seguidas no disponible: no se ha podido consultar la cuenta. No se puede cambiar de persona mientras no vuelva.",
    pickPersonTitle = "¿De quién es este teléfono?",
    pickPersonBody = "Elige la persona a la que pertenece este teléfono. Todo lo que se registre aquí — insulina, comidas, análisis — irá a su historial, y solo al suyo.",
    confirmTitle = "¿Bloquear en %s?",
    confirmBody = "Este teléfono quedará ligado definitivamente al historial de %s. Ya no habrá forma de cambiarlo ni de volver a teléfono de los padres: habría que desinstalar y reinstalar la aplicación.",
    confirmYes = "Bloquear definitivamente",
    confirmNo = "Cancelar",
    lockedForGood = "Bloqueo definitivo: solo una reinstalación completa de la aplicación puede quitarlo.",
    patientsPeek = "Puedes echar un vistazo a la glucosa de las otras personas de la cuenta: toca un nombre. Es solo una vista — tu historial sigue siendo el tuyo, no se cambia nada.",
    peekClose = "Cerrar",
    peekNote = "Solo una vista. Tus comidas, insulinas y análisis siguen en tu historial.",
    peekNoReading = "Sin medición reciente para esta persona.",
    peekJustNow = "ahora mismo",
    peekMinutesAgo = "hace %d min",
)

fun roleStringsFor(lang: Lang): RoleStrings = if (lang == Lang.ES) RoleStringsEs else RoleStringsFr
